
// This file has been generated by the GUI designer. Do not modify.
namespace pianocam
{
	public partial class KeyboardWidget
	{
		private global::Gtk.DrawingArea drawarea;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget pianocam.KeyboardWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "pianocam.KeyboardWidget";
			// Container child pianocam.KeyboardWidget.Gtk.Container+ContainerChild
			this.drawarea = new global::Gtk.DrawingArea();
			this.drawarea.Name = "drawarea";
			this.Add(this.drawarea);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.drawarea.ExposeEvent += new global::Gtk.ExposeEventHandler(this.OnDrawareaExposeEvent);
		}
	}
}
