
// This file has been generated by the GUI designer. Do not modify.
namespace pianocam
{
	public partial class ToolboxWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action goBackAction;

		private global::Gtk.Action goForwardAction;

		private global::Gtk.Action deleteAction;

		private global::Gtk.Action convertAction;

		private global::Gtk.Action goBackAction1;

		private global::Gtk.Action goForwardAction1;

		private global::Gtk.Action deleteAction1;

		private global::Gtk.Action convertAction1;

		private global::Gtk.ToggleAction refreshAction;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Toolbar toolbar1;

		private global::Gtk.HScale lefthandScale;

		private global::Gtk.HScale righthandScale;

		private global::Gtk.HBox hbox3;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label6;

		private global::Gtk.HBox hbox8;

		private global::Gtk.SpinButton def1;

		private global::Gtk.SpinButton def2;

		private global::Gtk.SpinButton def3;

		private global::Gtk.SpinButton def4;

		private global::Gtk.SpinButton def5;

		private global::Gtk.VSeparator vseparator1;

		private global::Gtk.VSeparator vseparator2;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Label label5;

		private global::Gtk.HBox hbox6;

		private global::Gtk.SpinButton def6;

		private global::Gtk.SpinButton def7;

		private global::Gtk.SpinButton def8;

		private global::Gtk.SpinButton def9;

		private global::Gtk.SpinButton def10;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget pianocam.ToolboxWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.goBackAction = new global::Gtk.Action("goBackAction", null, null, "gtk-go-back");
			w1.Add(this.goBackAction, null);
			this.goForwardAction = new global::Gtk.Action("goForwardAction", null, null, "gtk-go-forward");
			w1.Add(this.goForwardAction, null);
			this.deleteAction = new global::Gtk.Action("deleteAction", null, null, "gtk-delete");
			w1.Add(this.deleteAction, null);
			this.convertAction = new global::Gtk.Action("convertAction", null, null, "gtk-convert");
			w1.Add(this.convertAction, null);
			this.goBackAction1 = new global::Gtk.Action("goBackAction1", global::Mono.Unix.Catalog.GetString("Anterior"), null, "gtk-go-back");
			this.goBackAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Anterior");
			w1.Add(this.goBackAction1, null);
			this.goForwardAction1 = new global::Gtk.Action("goForwardAction1", global::Mono.Unix.Catalog.GetString("Próximo"), null, "gtk-go-forward");
			this.goForwardAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Próximo");
			w1.Add(this.goForwardAction1, null);
			this.deleteAction1 = new global::Gtk.Action("deleteAction1", null, null, "gtk-delete");
			w1.Add(this.deleteAction1, null);
			this.convertAction1 = new global::Gtk.Action("convertAction1", global::Mono.Unix.Catalog.GetString("Aplicar"), null, "gtk-convert");
			this.convertAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Aplicar");
			w1.Add(this.convertAction1, null);
			this.refreshAction = new global::Gtk.ToggleAction("refreshAction", global::Mono.Unix.Catalog.GetString("Instantâneo"), null, "gtk-refresh");
			this.refreshAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Instantâneo");
			w1.Add(this.refreshAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Events = ((global::Gdk.EventMask)(3072));
			this.Name = "pianocam.ToolboxWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Toolbox");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(3));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DestroyWithParent = true;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Container child pianocam.ToolboxWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><toolbar name='toolbar1'><toolitem name='goBackAction1' action='goBackAction1'/><toolitem name='goForwardAction1' action='goForwardAction1'/><toolitem name='deleteAction1' action='deleteAction1'/><toolitem name='convertAction1' action='convertAction1'/><toolitem name='refreshAction' action='refreshAction'/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.hbox1.Add(this.toolbar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.toolbar1]));
			w2.Position = 0;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lefthandScale = new global::Gtk.HScale(null);
			this.lefthandScale.CanFocus = true;
			this.lefthandScale.Name = "lefthandScale";
			this.lefthandScale.Adjustment.Upper = 100D;
			this.lefthandScale.Adjustment.PageIncrement = 10D;
			this.lefthandScale.Adjustment.StepIncrement = 1D;
			this.lefthandScale.DrawValue = true;
			this.lefthandScale.Digits = 0;
			this.lefthandScale.ValuePos = ((global::Gtk.PositionType)(2));
			this.vbox1.Add(this.lefthandScale);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.lefthandScale]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.righthandScale = new global::Gtk.HScale(null);
			this.righthandScale.CanFocus = true;
			this.righthandScale.Name = "righthandScale";
			this.righthandScale.Adjustment.Upper = 100D;
			this.righthandScale.Adjustment.PageIncrement = 10D;
			this.righthandScale.Adjustment.StepIncrement = 1D;
			this.righthandScale.DrawValue = true;
			this.righthandScale.Digits = 0;
			this.righthandScale.ValuePos = ((global::Gtk.PositionType)(2));
			this.vbox1.Add(this.righthandScale);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.righthandScale]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("ESQUERDA\n1                 2                 3                 4                 " +
					"5");
			this.label6.Justify = ((global::Gtk.Justification)(2));
			this.vbox2.Add(this.label6);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label6]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.def1 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.def1.CanFocus = true;
			this.def1.Name = "def1";
			this.def1.Adjustment.PageIncrement = 10D;
			this.def1.ClimbRate = 1D;
			this.def1.Numeric = true;
			this.hbox8.Add(this.def1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.def1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.def2 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.def2.CanFocus = true;
			this.def2.Name = "def2";
			this.def2.Adjustment.PageIncrement = 10D;
			this.def2.ClimbRate = 1D;
			this.def2.Numeric = true;
			this.hbox8.Add(this.def2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.def2]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.def3 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.def3.CanFocus = true;
			this.def3.Name = "def3";
			this.def3.Adjustment.PageIncrement = 10D;
			this.def3.ClimbRate = 1D;
			this.def3.Numeric = true;
			this.hbox8.Add(this.def3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.def3]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.def4 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.def4.CanFocus = true;
			this.def4.Name = "def4";
			this.def4.Adjustment.PageIncrement = 10D;
			this.def4.ClimbRate = 1D;
			this.def4.Numeric = true;
			this.hbox8.Add(this.def4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.def4]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.def5 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.def5.CanFocus = true;
			this.def5.Name = "def5";
			this.def5.Adjustment.PageIncrement = 10D;
			this.def5.ClimbRate = 1D;
			this.def5.Numeric = true;
			this.hbox8.Add(this.def5);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.def5]));
			w11.Position = 4;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox2.Add(this.hbox8);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox8]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox3.Add(this.vbox2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox2]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator();
			this.vseparator1.Name = "vseparator1";
			this.hbox3.Add(this.vseparator1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vseparator1]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator();
			this.vseparator2.Name = "vseparator2";
			this.hbox3.Add(this.vseparator2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vseparator2]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("DIREITA\n6                 7                 8                 9                 1" +
					"0");
			this.label5.Justify = ((global::Gtk.Justification)(2));
			this.vbox4.Add(this.label5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label5]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.def6 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.def6.CanFocus = true;
			this.def6.Name = "def6";
			this.def6.Adjustment.PageIncrement = 10D;
			this.def6.ClimbRate = 1D;
			this.def6.Numeric = true;
			this.hbox6.Add(this.def6);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.def6]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.def7 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.def7.CanFocus = true;
			this.def7.Name = "def7";
			this.def7.Adjustment.PageIncrement = 10D;
			this.def7.ClimbRate = 1D;
			this.def7.Numeric = true;
			this.hbox6.Add(this.def7);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.def7]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.def8 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.def8.CanFocus = true;
			this.def8.Name = "def8";
			this.def8.Adjustment.PageIncrement = 10D;
			this.def8.ClimbRate = 1D;
			this.def8.Numeric = true;
			this.hbox6.Add(this.def8);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.def8]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.def9 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.def9.CanFocus = true;
			this.def9.Name = "def9";
			this.def9.Adjustment.PageIncrement = 10D;
			this.def9.ClimbRate = 1D;
			this.def9.Numeric = true;
			this.hbox6.Add(this.def9);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.def9]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.def10 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.def10.CanFocus = true;
			this.def10.Name = "def10";
			this.def10.Adjustment.PageIncrement = 10D;
			this.def10.ClimbRate = 1D;
			this.def10.Numeric = true;
			this.hbox6.Add(this.def10);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.def10]));
			w21.Position = 4;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox4.Add(this.hbox6);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox6]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.hbox3.Add(this.vbox4);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox4]));
			w23.Position = 3;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w24.Position = 3;
			w24.Expand = false;
			w24.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 653;
			this.DefaultHeight = 600;
			this.Show();
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.OnKeyPressEvent);
			this.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.OnKeyReleaseEvent);
			this.goBackAction.Activated += new global::System.EventHandler(this.OnGoBackActionActivated);
			this.goForwardAction.Activated += new global::System.EventHandler(this.OnGoForwardActionActivated);
			this.deleteAction.Activated += new global::System.EventHandler(this.OnDeleteActionActivated);
			this.convertAction.Activated += new global::System.EventHandler(this.OnConvertActionActivated);
			this.goBackAction1.Activated += new global::System.EventHandler(this.OnGoBackActionActivated);
			this.goForwardAction1.Activated += new global::System.EventHandler(this.OnGoForwardActionActivated);
			this.deleteAction1.Activated += new global::System.EventHandler(this.OnDeleteActionActivated);
			this.convertAction1.Activated += new global::System.EventHandler(this.OnConvertActionActivated);
			this.refreshAction.Toggled += new global::System.EventHandler(this.OnRefreshActionToggled);
			this.lefthandScale.ValueChanged += new global::System.EventHandler(this.ValueChanged);
			this.righthandScale.ValueChanged += new global::System.EventHandler(this.ValueChanged);
			this.def1.ValueChanged += new global::System.EventHandler(this.ValueChanged);
			this.def2.ValueChanged += new global::System.EventHandler(this.ValueChanged);
			this.def3.ValueChanged += new global::System.EventHandler(this.ValueChanged);
			this.def4.ValueChanged += new global::System.EventHandler(this.ValueChanged);
			this.def5.ValueChanged += new global::System.EventHandler(this.ValueChanged);
			this.def6.ValueChanged += new global::System.EventHandler(this.ValueChanged);
			this.def7.ValueChanged += new global::System.EventHandler(this.ValueChanged);
			this.def8.ValueChanged += new global::System.EventHandler(this.ValueChanged);
			this.def9.ValueChanged += new global::System.EventHandler(this.ValueChanged);
			this.def10.ValueChanged += new global::System.EventHandler(this.ValueChanged);
		}
	}
}
