
// This file has been generated by the GUI designer. Do not modify.
namespace pianocam
{
	public partial class LoadWin
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Label label3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview1;

		private global::Gtk.HButtonBox hbuttonbox1;

		private global::Gtk.Button importButton;

		private global::Gtk.Label label1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget pianocam.LoadWin
			this.Name = "pianocam.LoadWin";
			this.Title = global::Mono.Unix.Catalog.GetString("PIANO CAM");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child pianocam.LoadWin.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("PIANO CAM\nCOMPUTER AIDED MUSIC");
			this.label3.Justify = ((global::Gtk.Justification)(2));
			this.vbox1.Add(this.label3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label3]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(20));
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow.Add(this.treeview1);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.Spacing = 5;
			this.hbuttonbox1.BorderWidth = ((uint)(10));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.importButton = new global::Gtk.Button();
			this.importButton.CanFocus = true;
			this.importButton.Name = "importButton";
			this.importButton.UseUnderline = true;
			this.importButton.Label = global::Mono.Unix.Catalog.GetString("IMPORT MIDI");
			this.hbuttonbox1.Add(this.importButton);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.importButton]));
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add(this.hbuttonbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbuttonbox1]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			w5.Padding = ((uint)(22));
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("LUIZ GUSTAVO PFITSCHER E FELDMANN");
			this.label1.Justify = ((global::Gtk.Justification)(2));
			this.vbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			w6.Padding = ((uint)(5));
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 508;
			this.DefaultHeight = 513;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.treeview1.RowActivated += new global::Gtk.RowActivatedHandler(this.OnTreeview1RowActivated);
			this.importButton.Clicked += new global::System.EventHandler(this.OnImportButtonClicked);
		}
	}
}
