
// This file has been generated by the GUI designer. Do not modify.
namespace pianocam
{
	public partial class TimelineViewWidget
	{
		private global::Gtk.DrawingArea DrawArea;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget pianocam.TimelineViewWidget
			global::Stetic.BinContainer.Attach(this);
			this.CanFocus = true;
			this.Events = ((global::Gdk.EventMask)(1280));
			this.Name = "pianocam.TimelineViewWidget";
			// Container child pianocam.TimelineViewWidget.Gtk.Container+ContainerChild
			this.DrawArea = new global::Gtk.DrawingArea();
			this.DrawArea.CanFocus = true;
			this.DrawArea.Events = ((global::Gdk.EventMask)(256));
			this.DrawArea.Name = "DrawArea";
			this.Add(this.DrawArea);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.OnKeyPressEvent);
			this.FocusOutEvent += new global::Gtk.FocusOutEventHandler(this.OnFocusOutEvent);
			this.ScrollEvent += new global::Gtk.ScrollEventHandler(this.OnScrollEvent);
			this.DrawArea.ExposeEvent += new global::Gtk.ExposeEventHandler(this.OnDrawAreaExposeEvent);
			this.DrawArea.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.OnDrawAreaButtonPressEvent);
		}
	}
}
