
// This file has been generated by the GUI designer. Do not modify.
namespace pianocam
{
	public partial class ToolsWindow
	{
		private global::Gtk.Notebook notebook1;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.ComboBox keySignatureTypeSelector;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label4;

		private global::Gtk.ComboBox originalKey;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Label label6;

		private global::Gtk.ComboBox desiredKey;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Label label8;

		private global::Gtk.SpinButton octaveShift;

		private global::Gtk.TextView textview1;

		private global::Gtk.HBox hbox3;

		private global::Gtk.ComboBox transposeTargeSelection;

		private global::Gtk.Button detectScaleButton;

		private global::Gtk.Button transposeButton;

		private global::Gtk.Button cancelButton1;

		private global::Gtk.Label label1;

		private global::Gtk.VBox vbox8;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textviewConformity;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Button correctButton;

		private global::Gtk.Label label2;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label label5;

		private global::Gtk.HBox hbox2;

		private global::Gtk.HScale timeRescaleRange;

		private global::Gtk.Button applyTimeRescale;

		private global::Gtk.Label label7;

		private global::Gtk.HBox hbox4;

		private global::Gtk.HScale gapRange;

		private global::Gtk.Button insertGapButton;

		private global::Gtk.Label label3;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Label label10;

		private global::Gtk.SpinButton timeTemperValue;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Button buttonRemoveTime;

		private global::Gtk.Button buttonAddTime;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Button trimBeforeBtn;

		private global::Gtk.Button trimAfterBtn;

		private global::Gtk.Label label11;

		private global::Gtk.Label label9;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget pianocam.ToolsWindow
			this.Name = "pianocam.ToolsWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Ferramentas");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.DestroyWithParent = true;
			// Container child pianocam.ToolsWindow.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 3;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.keySignatureTypeSelector = global::Gtk.ComboBox.NewText();
			this.keySignatureTypeSelector.AppendText(global::Mono.Unix.Catalog.GetString("Menor"));
			this.keySignatureTypeSelector.AppendText(global::Mono.Unix.Catalog.GetString("Maior"));
			this.keySignatureTypeSelector.Name = "keySignatureTypeSelector";
			this.keySignatureTypeSelector.Active = 1;
			this.hbox1.Add(this.keySignatureTypeSelector);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.keySignatureTypeSelector]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Escala de origem");
			this.label4.Justify = ((global::Gtk.Justification)(2));
			this.vbox2.Add(this.label4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label4]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.originalKey = global::Gtk.ComboBox.NewText();
			this.originalKey.Name = "originalKey";
			this.vbox2.Add(this.originalKey);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.originalKey]));
			w3.Position = 1;
			this.hbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Escala destino");
			this.label6.Justify = ((global::Gtk.Justification)(2));
			this.vbox4.Add(this.label6);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label6]));
			w5.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.desiredKey = global::Gtk.ComboBox.NewText();
			this.desiredKey.Name = "desiredKey";
			this.vbox4.Add(this.desiredKey);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.desiredKey]));
			w6.Position = 1;
			this.hbox1.Add(this.vbox4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox4]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Oitava");
			this.label8.Justify = ((global::Gtk.Justification)(2));
			this.vbox6.Add(this.label8);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label8]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.octaveShift = new global::Gtk.SpinButton(-5D, 5D, 1D);
			this.octaveShift.CanFocus = true;
			this.octaveShift.Name = "octaveShift";
			this.octaveShift.Adjustment.PageIncrement = 1D;
			this.octaveShift.ClimbRate = 1D;
			this.octaveShift.Numeric = true;
			this.octaveShift.SnapToTicks = true;
			this.vbox6.Add(this.octaveShift);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.octaveShift]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.hbox1.Add(this.vbox6);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox6]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.textview1 = new global::Gtk.TextView();
			this.textview1.Sensitive = false;
			this.textview1.Name = "textview1";
			this.textview1.Editable = false;
			this.textview1.CursorVisible = false;
			this.vbox1.Add(this.textview1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.textview1]));
			w12.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.transposeTargeSelection = global::Gtk.ComboBox.NewText();
			this.transposeTargeSelection.Name = "transposeTargeSelection";
			this.hbox3.Add(this.transposeTargeSelection);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.transposeTargeSelection]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.detectScaleButton = new global::Gtk.Button();
			this.detectScaleButton.CanFocus = true;
			this.detectScaleButton.Name = "detectScaleButton";
			this.detectScaleButton.UseUnderline = true;
			this.detectScaleButton.Label = global::Mono.Unix.Catalog.GetString("Detectar");
			this.hbox3.Add(this.detectScaleButton);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.detectScaleButton]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.transposeButton = new global::Gtk.Button();
			this.transposeButton.CanFocus = true;
			this.transposeButton.Name = "transposeButton";
			this.transposeButton.UseUnderline = true;
			this.transposeButton.Label = global::Mono.Unix.Catalog.GetString("Aplicar transposição");
			this.hbox3.Add(this.transposeButton);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.transposeButton]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.cancelButton1 = new global::Gtk.Button();
			this.cancelButton1.CanFocus = true;
			this.cancelButton1.Name = "cancelButton1";
			this.cancelButton1.UseUnderline = true;
			this.cancelButton1.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.hbox3.Add(this.cancelButton1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.cancelButton1]));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.notebook1.Add(this.vbox1);
			// Notebook tab
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Transposição");
			this.notebook1.SetTabLabel(this.vbox1, this.label1);
			this.label1.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textviewConformity = new global::Gtk.TextView();
			this.textviewConformity.CanFocus = true;
			this.textviewConformity.Name = "textviewConformity";
			this.textviewConformity.Editable = false;
			this.textviewConformity.CursorVisible = false;
			this.GtkScrolledWindow.Add(this.textviewConformity);
			this.vbox8.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.GtkScrolledWindow]));
			w20.Position = 0;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.correctButton = new global::Gtk.Button();
			this.correctButton.CanFocus = true;
			this.correctButton.Name = "correctButton";
			this.correctButton.UseUnderline = true;
			this.correctButton.Label = global::Mono.Unix.Catalog.GetString("Analisar e Corrigir");
			this.hbox5.Add(this.correctButton);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.correctButton]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox8.Add(this.hbox5);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox5]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.notebook1.Add(this.vbox8);
			global::Gtk.Notebook.NotebookChild w23 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox8]));
			w23.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Conformidade");
			this.notebook1.SetTabLabel(this.vbox8, this.label2);
			this.label2.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Alterar velocidade");
			this.vbox3.Add(this.label5);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label5]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.timeRescaleRange = new global::Gtk.HScale(null);
			this.timeRescaleRange.CanFocus = true;
			this.timeRescaleRange.Name = "timeRescaleRange";
			this.timeRescaleRange.Adjustment.Lower = 0.5D;
			this.timeRescaleRange.Adjustment.Upper = 2D;
			this.timeRescaleRange.Adjustment.PageIncrement = 0.1D;
			this.timeRescaleRange.Adjustment.StepIncrement = 0.1D;
			this.timeRescaleRange.Adjustment.Value = 1D;
			this.timeRescaleRange.DrawValue = true;
			this.timeRescaleRange.Digits = 2;
			this.timeRescaleRange.ValuePos = ((global::Gtk.PositionType)(2));
			this.hbox2.Add(this.timeRescaleRange);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.timeRescaleRange]));
			w25.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.applyTimeRescale = new global::Gtk.Button();
			this.applyTimeRescale.CanFocus = true;
			this.applyTimeRescale.Name = "applyTimeRescale";
			this.applyTimeRescale.UseUnderline = true;
			this.applyTimeRescale.Label = global::Mono.Unix.Catalog.GetString("Aplicar");
			this.hbox2.Add(this.applyTimeRescale);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.applyTimeRescale]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox3.Add(this.hbox2);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Inserir lacunas (ms)");
			this.vbox3.Add(this.label7);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label7]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.gapRange = new global::Gtk.HScale(null);
			this.gapRange.CanFocus = true;
			this.gapRange.Name = "gapRange";
			this.gapRange.Adjustment.Upper = 100D;
			this.gapRange.Adjustment.PageIncrement = 10D;
			this.gapRange.Adjustment.StepIncrement = 100D;
			this.gapRange.Adjustment.Value = 50D;
			this.gapRange.DrawValue = true;
			this.gapRange.Digits = 0;
			this.gapRange.ValuePos = ((global::Gtk.PositionType)(2));
			this.hbox4.Add(this.gapRange);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.gapRange]));
			w29.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.insertGapButton = new global::Gtk.Button();
			this.insertGapButton.CanFocus = true;
			this.insertGapButton.Name = "insertGapButton";
			this.insertGapButton.UseUnderline = true;
			this.insertGapButton.Label = global::Mono.Unix.Catalog.GetString("Aplicar");
			this.hbox4.Add(this.insertGapButton);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.insertGapButton]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			this.vbox3.Add(this.hbox4);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
			w31.Position = 3;
			w31.Expand = false;
			w31.Fill = false;
			this.notebook1.Add(this.vbox3);
			global::Gtk.Notebook.NotebookChild w32 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox3]));
			w32.Position = 2;
			// Notebook tab
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Tempo");
			this.notebook1.SetTabLabel(this.vbox3, this.label3);
			this.label3.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Segundos após o cursor:");
			this.vbox5.Add(this.label10);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label10]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.timeTemperValue = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.timeTemperValue.CanFocus = true;
			this.timeTemperValue.Name = "timeTemperValue";
			this.timeTemperValue.Adjustment.PageIncrement = 10D;
			this.timeTemperValue.ClimbRate = 0.5D;
			this.timeTemperValue.Numeric = true;
			this.timeTemperValue.Value = 3D;
			this.vbox5.Add(this.timeTemperValue);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.timeTemperValue]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.buttonRemoveTime = new global::Gtk.Button();
			this.buttonRemoveTime.CanFocus = true;
			this.buttonRemoveTime.Name = "buttonRemoveTime";
			this.buttonRemoveTime.UseUnderline = true;
			this.buttonRemoveTime.Label = global::Mono.Unix.Catalog.GetString("Remover tempo");
			this.hbox6.Add(this.buttonRemoveTime);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.buttonRemoveTime]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.buttonAddTime = new global::Gtk.Button();
			this.buttonAddTime.CanFocus = true;
			this.buttonAddTime.Name = "buttonAddTime";
			this.buttonAddTime.UseUnderline = true;
			this.buttonAddTime.Label = global::Mono.Unix.Catalog.GetString("Adicionar tempo");
			this.hbox6.Add(this.buttonAddTime);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.buttonAddTime]));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			this.vbox5.Add(this.hbox6);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox6]));
			w37.Position = 2;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.trimBeforeBtn = new global::Gtk.Button();
			this.trimBeforeBtn.CanFocus = true;
			this.trimBeforeBtn.Name = "trimBeforeBtn";
			this.trimBeforeBtn.UseUnderline = true;
			this.trimBeforeBtn.Label = global::Mono.Unix.Catalog.GetString("Eliminar antes");
			this.hbox7.Add(this.trimBeforeBtn);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.trimBeforeBtn]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.trimAfterBtn = new global::Gtk.Button();
			this.trimAfterBtn.CanFocus = true;
			this.trimAfterBtn.Name = "trimAfterBtn";
			this.trimAfterBtn.UseUnderline = true;
			this.trimAfterBtn.Label = global::Mono.Unix.Catalog.GetString("Eliminar após");
			this.hbox7.Add(this.trimAfterBtn);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.trimAfterBtn]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			this.vbox5.Add(this.hbox7);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
			w40.PackType = ((global::Gtk.PackType)(1));
			w40.Position = 3;
			w40.Expand = false;
			w40.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Cortar");
			this.vbox5.Add(this.label11);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label11]));
			w41.PackType = ((global::Gtk.PackType)(1));
			w41.Position = 4;
			w41.Expand = false;
			w41.Fill = false;
			this.notebook1.Add(this.vbox5);
			global::Gtk.Notebook.NotebookChild w42 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox5]));
			w42.Position = 3;
			// Notebook tab
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Linha do tempo");
			this.notebook1.SetTabLabel(this.vbox5, this.label9);
			this.label9.ShowAll();
			this.Add(this.notebook1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 536;
			this.DefaultHeight = 300;
			this.Show();
			this.keySignatureTypeSelector.Changed += new global::System.EventHandler(this.OnTransposeChanged);
			this.originalKey.Changed += new global::System.EventHandler(this.OnTransposeChanged);
			this.desiredKey.Changed += new global::System.EventHandler(this.OnTransposeChanged);
			this.octaveShift.ValueChanged += new global::System.EventHandler(this.OnTransposeChanged);
			this.detectScaleButton.Clicked += new global::System.EventHandler(this.OnDetectScaleButtonClicked);
			this.transposeButton.Clicked += new global::System.EventHandler(this.transposeRun);
			this.cancelButton1.Activated += new global::System.EventHandler(this.closeWindow);
			this.correctButton.Clicked += new global::System.EventHandler(this.OnCorrectButtonClicked);
			this.applyTimeRescale.Clicked += new global::System.EventHandler(this.OnApplyTimeRescaleClicked);
			this.insertGapButton.Clicked += new global::System.EventHandler(this.OnInsertGapButtonClicked);
			this.buttonRemoveTime.Clicked += new global::System.EventHandler(this.OnButtonRemoveTimeClicked);
			this.buttonAddTime.Clicked += new global::System.EventHandler(this.OnButtonAddTimeClicked);
			this.trimBeforeBtn.Clicked += new global::System.EventHandler(this.OnTrimBeforeBtnClicked);
			this.trimAfterBtn.Clicked += new global::System.EventHandler(this.OnTrimAfterBtnClicked);
		}
	}
}
