
// This file has been generated by the GUI designer. Do not modify.
namespace pianocam
{
	public partial class SequenceWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action saveAction;

		private global::Gtk.Action executeAction;

		private global::Gtk.Action gotoLastAction;

		private global::Gtk.Action stopAction;

		private global::Gtk.Action networkAction;

		private global::Gtk.Action toolsAction;

		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Toolbar toolbar1;

		private global::Gtk.ComboBox combobox1;

		private global::Gtk.HBox hbox3;

		private global::Gtk.VBox vbox3;

		private global::pianocam.TimelineViewWidget timelineviewwidget1;

		private global::pianocam.KeyboardWidget keyboardwidget1;

		private global::Gtk.DrawingArea drawingarea3;

		private global::Gtk.HBox hbox2;

		private global::Gtk.HScale hscaleZoom;

		private global::Gtk.VScale vscale1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget pianocam.SequenceWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.saveAction = new global::Gtk.Action("saveAction", global::Mono.Unix.Catalog.GetString("Salvar"), null, "gtk-floppy");
			this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Salvar");
			w1.Add(this.saveAction, null);
			this.executeAction = new global::Gtk.Action("executeAction", global::Mono.Unix.Catalog.GetString("Configurações"), null, "gtk-preferences");
			this.executeAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Configurações");
			w1.Add(this.executeAction, null);
			this.gotoLastAction = new global::Gtk.Action("gotoLastAction", global::Mono.Unix.Catalog.GetString("Play (local)"), null, "gtk-media-play");
			this.gotoLastAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Play (local)");
			w1.Add(this.gotoLastAction, null);
			this.stopAction = new global::Gtk.Action("stopAction", null, null, "gtk-stop");
			w1.Add(this.stopAction, null);
			this.networkAction = new global::Gtk.Action("networkAction", global::Mono.Unix.Catalog.GetString("Executar"), null, "gtk-network");
			this.networkAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Conectar");
			w1.Add(this.networkAction, null);
			this.toolsAction = new global::Gtk.Action("toolsAction", global::Mono.Unix.Catalog.GetString("Ferramentas"), null, "gtk-properties");
			this.toolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Ferramentas");
			w1.Add(this.toolsAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "pianocam.SequenceWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("PIANO CAM");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child pianocam.SequenceWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><toolbar name='toolbar1'><toolitem name='saveAction' action='saveAction'/><toolitem name='executeAction' action='executeAction'/><toolitem name='gotoLastAction' action='gotoLastAction'/><toolitem name='stopAction' action='stopAction'/><toolitem name='networkAction' action='networkAction'/><toolitem name='toolsAction' action='toolsAction'/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.hbox1.Add(this.toolbar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.toolbar1]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText();
			this.combobox1.Name = "combobox1";
			this.hbox1.Add(this.combobox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.combobox1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.timelineviewwidget1 = new global::pianocam.TimelineViewWidget();
			this.timelineviewwidget1.CanFocus = true;
			this.timelineviewwidget1.Events = ((global::Gdk.EventMask)(1280));
			this.timelineviewwidget1.Name = "timelineviewwidget1";
			this.timelineviewwidget1.CurrentTimeMs = 0F;
			this.timelineviewwidget1.CursorTimeMs = 0F;
			this.vbox3.Add(this.timelineviewwidget1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.timelineviewwidget1]));
			w5.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.keyboardwidget1 = new global::pianocam.KeyboardWidget();
			this.keyboardwidget1.HeightRequest = 60;
			this.keyboardwidget1.Sensitive = false;
			this.keyboardwidget1.Events = ((global::Gdk.EventMask)(256));
			this.keyboardwidget1.Name = "keyboardwidget1";
			this.vbox3.Add(this.keyboardwidget1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.keyboardwidget1]));
			w6.Position = 1;
			w6.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.drawingarea3 = new global::Gtk.DrawingArea();
			this.drawingarea3.HeightRequest = 8;
			this.drawingarea3.Name = "drawingarea3";
			this.vbox3.Add(this.drawingarea3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.drawingarea3]));
			w7.Position = 2;
			w7.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hscaleZoom = new global::Gtk.HScale(null);
			this.hscaleZoom.WidthRequest = 142;
			this.hscaleZoom.CanFocus = true;
			this.hscaleZoom.Name = "hscaleZoom";
			this.hscaleZoom.Adjustment.Lower = 50D;
			this.hscaleZoom.Adjustment.Upper = 200D;
			this.hscaleZoom.Adjustment.PageIncrement = 10D;
			this.hscaleZoom.Adjustment.StepIncrement = 10D;
			this.hscaleZoom.Adjustment.Value = 100D;
			this.hscaleZoom.DrawValue = true;
			this.hscaleZoom.Digits = 0;
			this.hscaleZoom.ValuePos = ((global::Gtk.PositionType)(0));
			this.hbox2.Add(this.hscaleZoom);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hscaleZoom]));
			w8.PackType = ((global::Gtk.PackType)(1));
			w8.Position = 2;
			w8.Expand = false;
			this.vbox3.Add(this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			this.hbox3.Add(this.vbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox3]));
			w10.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vscale1 = new global::Gtk.VScale(null);
			this.vscale1.CanFocus = true;
			this.vscale1.Name = "vscale1";
			this.vscale1.Adjustment.Upper = 100D;
			this.vscale1.Adjustment.PageIncrement = 10D;
			this.vscale1.Adjustment.StepIncrement = 1D;
			this.vscale1.DrawValue = false;
			this.vscale1.Digits = 0;
			this.vscale1.ValuePos = ((global::Gtk.PositionType)(2));
			this.hbox3.Add(this.vscale1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vscale1]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
			w12.Position = 1;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 813;
			this.DefaultHeight = 518;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.ScrollEvent += new global::Gtk.ScrollEventHandler(this.OnScrollEvent);
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.OnKeyPressEvent);
			this.saveAction.Activated += new global::System.EventHandler(this.OnSaveActionActivated);
			this.executeAction.Activated += new global::System.EventHandler(this.OnPreferencesActionActivated);
			this.gotoLastAction.Activated += new global::System.EventHandler(this.OnGotoLastActionActivated);
			this.stopAction.Activated += new global::System.EventHandler(this.OnStopActionActivated);
			this.networkAction.Activated += new global::System.EventHandler(this.OnNetworkActionActivated);
			this.toolsAction.Activated += new global::System.EventHandler(this.OnToolsActionActivated);
			this.combobox1.Changed += new global::System.EventHandler(this.OnCombobox1Changed);
			this.hscaleZoom.ValueChanged += new global::System.EventHandler(this.OnHscaleZoomValueChanged);
			this.vscale1.ValueChanged += new global::System.EventHandler(this.OnVscale1ValueChanged);
		}
	}
}
